In [62]:
import pandas as pd
df = pd.read_csv("./data/Sonoma/07-14-2025.csv", delimiter='\t')
# df = pd.read_csv("./data/Sonoma/07-14-2025.csv", delimiter='\t')
df[df["POS"] <= 40]

,POS,DRIVER,CAR,MANUFACTURER,LAPS,START,LED,PTS,BONUS,PENALTY
0,1,Shane van Gisbergen,88,Chevrolet,110,1,97,59,19,0
1,2,Chase Briscoe,19,Toyota,110,2,2,44,9,0
2,3,Chase Elliott,9,Chevrolet,110,13,0,35,1,0
3,4,Michael McDowell,71,Chevrolet,110,15,3,33,0,0
4,5,Christopher Bell,20,Toyota,110,10,1,32,0,0
5,6,Tyler Reddick,45,Toyota,110,8,0,31,0,0
6,7,Ty Gibbs,54,Toyota,110,6,0,32,2,0
7,8,William Byron,24,Chevrolet,110,3,0,36,7,0
8,9,Joey Logano,22,Ford,110,22,0,28,0,0
9,10,Kyle Busch,8,Chevrolet,110,17,0,35,8,0
10,11,Brad Keselowski,6,Ford,110,21,0,26,0,0
11,12,Ryan Preece,60,Ford,110,20,0,25,0,0
12,13,Josh Berry,21,Ford,110,25,0,24,0,0
13,14,Daniel Suarez,99,Chevrolet,110,19,0,23,0,0
14,15,Justin Haley,7,Chevrolet,110,29,0,23,1,0
15,16,Chris Buescher,17,Ford,110,14,0,24,3,0
16,17,Ty Dillon,10,Chevrolet,110,26,0,29,9,0
17,18,AJ Allmendinger,16,Chevrolet,110,5,0,19,0,0
18,19,Alex Bowman,48,Chevrolet,110,9,0,18,0,0
19,20,Denny Hamlin,11,Toyota,110,16,0,17,0,0
20,21,Austin Dillon,3,Chevrolet,110,33,0,16,0,0
21,22,Todd Gilliland,34,Ford,110,35,0,15,0,0
22,23,Cole Custer,41,Chevrolet,110,27,0,14,0,0
23,24,Ross Chastain,1,Chevrolet,110,4,4,23,10,0
24,25,Riley Herbst,35,Toyota,110,28,0,12,0,0
25,26,Bubba Wallace,23,Toyota,110,30,0,26,15,0
26,27,Zane Smith,38,Ford,110,12,0,10,0,0
27,28,John Hunter Nemechek,42,Toyota,110,18,0,9,0,0
28,29,Erik Jones,43,Toyota,110,31,0,8,0,0
29,30,Austin Cindric,2,Ford,110,24,0,7,0,0
30,31,Katherine Legge,78,Chevrolet,110,37,0,6,0,0
31,32,Carson Hocevar,77,Chevrolet,110,23,0,5,0,0
32,33,Ricky Stenhouse Jr.,47,Chevrolet,110,34,0,17,13,0
33,34,Cody Ware,51,Chevrolet,108,36,0,3,0,0
34,35,Kyle Larson,5,Chevrolet,108,11,3,11,9,0
35,36,Ryan Blaney,12,Ford,106,7,0,6,5,0
36,37,Noah Gragson,4,Ford,99,32,0,1,0,0

In [76]:
df.groupby("MANUFACTURER")["POS"].describe()

              count       mean        std  min    25%   50%    75%   max
MANUFACTURER
Chevrolet      18.0  19.000000  11.082578  1.0  11.00  18.5  29.25  35.0
Ford           10.0  21.300000  10.604506  9.0  12.25  19.0  29.25  37.0
Toyota          9.0  16.444444  11.215069  2.0   6.00  20.0  26.00  29.0

In [83]:
import os
import glob

path = "./data/Sonoma/"
csv_files = glob.glob(path + "*.csv")
print(os.listdir("./data/Sonoma/"))
df_list = (pd.read_csv(file, delimiter='\t') for file in csv_files)
# print(type(df_list))
# for x in df_list:
    # print(x)
df = pd.concat(df_list, ignore_index=True)
df

#combined_df = pd.concat(df_list, ignore_index=True)

['06-09-2024.csv', '06-11-2023.csv', '07-14-2025.csv']

,POS,DRIVER,CAR,MANUFACTURER,LAPS,START,LED,PTS,BONUS,PENALTY
0,1,Kyle Larson,5,Chevrolet,110,5,19,48,8,0
1,2,Michael McDowell,34,Ford,110,12,0,40,5,0
2,3,Chris Buescher,17,Ford,110,26,32,44,10,0
3,4,Chase Elliott,9,Chevrolet,110,4,3,40,7,0
4,5,Ross Chastain,1,Chevrolet,110,9,0,36,4,0
...,...,...,...,...,...,...,...,...,...,...
106,33,Ricky Stenhouse Jr.,47,Chevrolet,110,34,0,17,13,0
107,34,Cody Ware,51,Chevrolet,108,36,0,3,0,0
108,35,Kyle Larson,5,Chevrolet,108,11,3,11,9,0
109,36,Ryan Blaney,12,Ford,106,7,0,6,5,0
110,37,Noah Gragson,4,Ford,99,32,0,1,0,0

In [66]:
df.groupby("MANUFACTURER")["POS"].describe()

              count       mean        std  min   25%   50%   75%   max
MANUFACTURER
Chevrolet      49.0  17.489796  10.239064  1.0  10.0  17.0  24.0  36.0
Ford           39.0  20.615385  10.754718  2.0  11.5  22.0  29.5  37.0
Toyota         23.0  19.521739  11.762303  1.0   8.5  20.0  28.5  38.0

In [70]:
df.groupby("DRIVER").describe()
# df[df["POS"] <= 10]
# df['combined']

                       POS                                                  \
                     count       mean        std   min    25%   50%    75%
DRIVER
AJ Allmendinger        3.0  10.000000   6.928203   6.0   6.00   6.0  12.00
Alex Bowman            3.0  16.333333   2.309401  15.0  15.00  15.0  17.00
Andy Lally             1.0  35.000000        NaN  35.0  35.00  35.0  35.00
Aric Almirola          1.0  28.000000        NaN  28.0  28.00  28.0  28.00
Austin Cindric         3.0  25.666667   4.041452  22.0  23.50  25.0  27.50
Austin Dillon          3.0  25.333333   9.291573  19.0  20.00  21.0  28.50
Brad Keselowski        3.0  13.333333   2.516611  11.0  12.00  13.0  14.50
Bubba Wallace          3.0  21.000000   4.582576  17.0  18.50  20.0  23.00
Cam Waters             1.0  35.000000        NaN  35.0  35.00  35.0  35.00
Carson Hocevar         2.0  24.500000  10.606602  17.0  20.75  24.5  28.25
Chase Briscoe          3.0  21.666667  17.214335   2.0  15.50  29.0  31.50
Chase Elliott          3.0   4.000000   1.000000   3.0   3.50   4.0   4.50
Chris Buescher         3.0   7.666667   7.234178   3.0   3.50   4.0  10.00
Christopher Bell       3.0   7.666667   2.309401   5.0   7.00   9.0   9.00
Cody Ware              1.0  34.000000        NaN  34.0  34.00  34.0  34.00
Cole Custer            1.0  23.000000        NaN  23.0  23.00  23.0  23.00
Corey LaJoie           2.0  15.500000   6.363961  11.0  13.25  15.5  17.75
Daniel Hemric          1.0  28.000000        NaN  28.0  28.00  28.0  28.00
Daniel Suarez          3.0  16.666667   4.618802  14.0  14.00  14.0  18.00
Denny Hamlin           3.0  31.333333   9.865766  20.0  28.00  36.0  37.00
Erik Jones             3.0  26.666667   6.806859  19.0  24.00  29.0  30.50
Grant Enfinger         1.0  26.000000        NaN  26.0  26.00  26.0  26.00
Harrison Burton        2.0  26.000000   1.414214  25.0  25.50  26.0  26.50
Joey Logano            3.0  11.000000   9.165151   3.0   6.00   9.0  15.00
John Hunter Nemechek   2.0  28.500000   0.707107  28.0  28.25  28.5  28.75
Josh Berry             2.0  22.500000  13.435029  13.0  17.75  22.5  27.25
Josh Bilicki           1.0  30.000000        NaN  30.0  30.00  30.0  30.00
Justin Haley           3.0  23.000000   9.165151  15.0  18.00  21.0  27.00
Katherine Legge        1.0  31.000000        NaN  31.0  31.00  31.0  31.00
Kaz Grala              1.0  23.000000        NaN  23.0  23.00  23.0  23.00
Kevin Harvick          1.0  11.000000        NaN  11.0  11.00  11.0  11.00
Kyle Busch             3.0   8.000000   5.291503   2.0   6.00  10.0  11.00
Kyle Larson            3.0  14.666667  17.953644   1.0   4.50   8.0  21.50
Martin Truex Jr.       2.0  14.000000  18.384776   1.0   7.50  14.0  20.50
Michael McDowell       3.0   4.333333   2.516611   2.0   3.00   4.0   5.50
Noah Gragson           2.0  31.500000   7.778175  26.0  28.75  31.5  34.25
Ricky Stenhouse Jr.    3.0  23.000000  10.535654  12.0  18.00  24.0  28.50
Riley Herbst           1.0  25.000000        NaN  25.0  25.00  25.0  25.00
Ross Chastain          3.0  13.000000   9.848858   5.0   7.50  10.0  17.00
Ryan Blaney            3.0  24.666667  15.502688   7.0  19.00  31.0  33.50
Ryan Preece            3.0  14.333333   3.214550  12.0  12.50  13.0  15.50
Shane van Gisbergen    1.0   1.000000        NaN   1.0   1.00   1.0   1.00
Todd Gilliland         3.0  18.666667   7.571878  10.0  16.00  22.0  23.00
Ty Dillon              2.0  20.000000   4.242641  17.0  18.50  20.0  21.50
Ty Gibbs               3.0  20.666667  15.176737   7.0  12.50  18.0  27.50
Tyler Reddick          3.0  15.666667  15.044379   6.0   7.00   8.0  20.50
Will Brown             1.0  31.000000        NaN  31.0  31.00  31.0  31.00
William Byron          3.0  17.333333  11.372481   8.0  11.00  14.0  22.00
Zane Smith             3.0  25.666667   9.073772  16.0  21.50  27.0  30.50

                             CAR             ...  BONUS       PENALTY       \
                       max count       mean  ...    75%   max   count mean
DRIVER                                       ...
AJ Allmendinger       18.0   3.0  16.000000  ...   3.50   7.0     3.0  0.0
Alex Bowman           19.0   3.0  48.000000  ...   4.00   6.0     3.0  0.0
Andy Lally            35.0   1.0  15.000000  ...   0.00   0.0     1.0  0.0
Aric Almirola         28.0   1.0  10.000000  ...   0.00   0.0     1.0  0.0
Austin Cindric        30.0   3.0   2.000000  ...   0.00   0.0     3.0  0.0
Austin Dillon         36.0   3.0   3.000000  ...   2.50   5.0     3.0  0.0
Brad Keselowski       16.0   3.0   6.000000  ...   2.50   5.0     3.0  0.0
Bubba Wallace         26.0   3.0  23.000000  ...   7.50  15.0     3.0  0.0
Cam Waters            35.0   1.0  60.000000  ...   0.00   0.0     1.0  0.0
Carson Hocevar        32.0   2.0  77.000000  ...   0.00   0.0     2.0  0.0
Chase Briscoe         34.0   3.0  15.666667  ...   4.50   9.0     3.0  0.0
Chase Elliott          5.0   3.0   9.000000  ...   4.00   7.0     3.0  0.0
Chris Buescher        16.0   3.0  17.000000  ...   7.00  10.0     3.0  0.0
Christopher Bell       9.0   3.0  20.000000  ...   5.00  10.0     3.0  0.0
Cody Ware             34.0   1.0  51.000000  ...   0.00   0.0     1.0  0.0
Cole Custer           23.0   1.0  41.000000  ...   0.00   0.0     1.0  0.0
Corey LaJoie          20.0   2.0   7.000000  ...   1.50   2.0     2.0  0.0
Daniel Hemric         28.0   1.0  31.000000  ...   0.00   0.0     1.0  0.0
Daniel Suarez         22.0   3.0  99.000000  ...   1.50   3.0     3.0  0.0
Denny Hamlin          38.0   3.0  11.000000  ...   5.00  10.0     3.0  0.0
Erik Jones            32.0   3.0  43.000000  ...   2.00   4.0     3.0  0.0
Grant Enfinger        26.0   1.0  42.000000  ...   0.00   0.0     1.0  0.0
Harrison Burton       27.0   2.0  21.000000  ...   0.75   1.0     2.0  0.0
Joey Logano           21.0   3.0  22.000000  ...   5.50   9.0     3.0  0.0
John Hunter Nemechek  29.0   2.0  42.000000  ...   0.00   0.0     2.0  0.0
Josh Berry            32.0   2.0  12.500000  ...   0.00   0.0     2.0  0.0
Josh Bilicki          30.0   1.0  78.000000  ...   0.00   0.0     1.0  0.0
Justin Haley          33.0   3.0  29.666667  ...   0.50   1.0     3.0  0.0
Katherine Legge       31.0   1.0  78.000000  ...   0.00   0.0     1.0  0.0
Kaz Grala             23.0   1.0  15.000000  ...   0.00   0.0     1.0  0.0
Kevin Harvick         11.0   1.0   4.000000  ...   1.00   1.0     1.0  0.0
Kyle Busch            12.0   3.0   8.000000  ...   9.00  10.0     3.0  0.0
Kyle Larson           35.0   3.0   5.000000  ...   8.50   9.0     3.0  0.0
Martin Truex Jr.      27.0   2.0  19.000000  ...  11.75  13.0     2.0  0.0
Michael McDowell       7.0   3.0  46.333333  ...   7.00   9.0     3.0  0.0
Noah Gragson          37.0   2.0   7.000000  ...   0.00   0.0     2.0  0.0
Ricky Stenhouse Jr.   33.0   3.0  47.000000  ...  10.00  13.0     3.0  0.0
Riley Herbst          25.0   1.0  35.000000  ...   0.00   0.0     1.0  0.0
Ross Chastain         24.0   3.0   1.000000  ...   9.00  10.0     3.0  0.0
Ryan Blaney           36.0   3.0  12.000000  ...   7.00   9.0     3.0  0.0
Ryan Preece           18.0   3.0  47.333333  ...   4.50   9.0     3.0  0.0
Shane van Gisbergen    1.0   1.0  88.000000  ...  19.00  19.0     1.0  0.0
Todd Gilliland        24.0   3.0  41.000000  ...   2.00   4.0     3.0  0.0
Ty Dillon             23.0   2.0  43.500000  ...   6.75   9.0     2.0  0.0
Ty Gibbs              37.0   3.0  54.000000  ...   2.50   3.0     3.0  0.0
Tyler Reddick         33.0   3.0  45.000000  ...   7.50  10.0     3.0  0.0
Will Brown            31.0   1.0  33.000000  ...   0.00   0.0     1.0  0.0
William Byron         30.0   3.0  24.000000  ...   7.00   7.0     3.0  0.0
Zane Smith            34.0   3.0  49.000000  ...   0.00   0.0     3.0  0.0


                      std  min  25%  50%  75%  max
DRIVER
AJ Allmendinger       0.0  0.0  0.0  0.0  0.0  0.0
Alex Bowman           0.0  0.0  0.0  0.0  0.0  0.0
Andy Lally            NaN  0.0  0.0  0.0  0.0  0.0
Aric Almirola         NaN  0.0  0.0  0.0  0.0  0.0
Austin Cindric        0.0  0.0  0.0  0.0  0.0  0.0
Austin Dillon         0.0  0.0  0.0  0.0  0.0  0.0
Brad Keselowski       0.0  0.0  0.0  0.0  0.0  0.0
Bubba Wallace         0.0  0.0  0.0  0.0  0.0  0.0
Cam Waters            NaN  0.0  0.0  0.0  0.0  0.0
Carson Hocevar        0.0  0.0  0.0  0.0  0.0  0.0
Chase Briscoe         0.0  0.0  0.0  0.0  0.0  0.0
Chase Elliott         0.0  0.0  0.0  0.0  0.0  0.0
Chris Buescher        0.0  0.0  0.0  0.0  0.0  0.0
Christopher Bell      0.0  0.0  0.0  0.0  0.0  0.0
Cody Ware             NaN  0.0  0.0  0.0  0.0  0.0
Cole Custer           NaN  0.0  0.0  0.0  0.0  0.0
Corey LaJoie          0.0  0.0  0.0  0.0  0.0  0.0
Daniel Hemric         NaN  0.0  0.0  0.0  0.0  0.0
Daniel Suarez         0.0  0.0  0.0  0.0  0.0  0.0
Denny Hamlin          0.0  0.0  0.0  0.0  0.0  0.0
Erik Jones            0.0  0.0  0.0  0.0  0.0  0.0
Grant Enfinger        NaN  0.0  0.0  0.0  0.0  0.0
Harrison Burton       0.0  0.0  0.0  0.0  0.0  0.0
Joey Logano           0.0  0.0  0.0  0.0  0.0  0.0
John Hunter Nemechek  0.0  0.0  0.0  0.0  0.0  0.0
Josh Berry            0.0  0.0  0.0  0.0  0.0  0.0
Josh Bilicki          NaN  0.0  0.0  0.0  0.0  0.0
Justin Haley          0.0  0.0  0.0  0.0  0.0  0.0
Katherine Legge       NaN  0.0  0.0  0.0  0.0  0.0
Kaz Grala             NaN  0.0  0.0  0.0  0.0  0.0
Kevin Harvick         NaN  0.0  0.0  0.0  0.0  0.0
Kyle Busch            0.0  0.0  0.0  0.0  0.0  0.0
Kyle Larson           0.0  0.0  0.0  0.0  0.0  0.0
Martin Truex Jr.      0.0  0.0  0.0  0.0  0.0  0.0
Michael McDowell      0.0  0.0  0.0  0.0  0.0  0.0
Noah Gragson          0.0  0.0  0.0  0.0  0.0  0.0
Ricky Stenhouse Jr.   0.0  0.0  0.0  0.0  0.0  0.0
Riley Herbst          NaN  0.0  0.0  0.0  0.0  0.0
Ross Chastain         0.0  0.0  0.0  0.0  0.0  0.0
Ryan Blaney           0.0  0.0  0.0  0.0  0.0  0.0
Ryan Preece           0.0  0.0  0.0  0.0  0.0  0.0
Shane van Gisbergen   NaN  0.0  0.0  0.0  0.0  0.0
Todd Gilliland        0.0  0.0  0.0  0.0  0.0  0.0
Ty Dillon             0.0  0.0  0.0  0.0  0.0  0.0
Ty Gibbs              0.0  0.0  0.0  0.0  0.0  0.0
Tyler Reddick         0.0  0.0  0.0  0.0  0.0  0.0
Will Brown            NaN  0.0  0.0  0.0  0.0  0.0
William Byron         0.0  0.0  0.0  0.0  0.0  0.0
Zane Smith            0.0  0.0  0.0  0.0  0.0  0.0

[49 rows x 64 columns]

In [65]:
drop_columns = ["PTS","BONUS","LAPS","LED"]
df1 = pd.read_csv("./data/Sonoma/06-09-2024.csv", delimiter='\t')
df1.drop(drop_columns,axis=1,inplace=True)
# df1
df2 = pd.read_csv("./data/Sonoma/07-14-2025.csv", delimiter='\t')
df2.drop(drop_columns, axis=1, inplace=True)
# df2
df_merged = pd.merge(df2, df1, on="DRIVER", how="left")
# df.merged.drop("DRIVER", axis=1, inplace=True)
df_merged

,POS_x,DRIVER,CAR_x,MANUFACTURER_x,START_x,PENALTY_x,POS_y,CAR_y,MANUFACTURER_y,START_y,PENALTY_y
0,1,Shane van Gisbergen,88,Chevrolet,1,0,NaN,NaN,NaN,NaN,NaN
1,2,Chase Briscoe,19,Toyota,2,0,34.0,14.0,Ford,23.0,0.0
2,3,Chase Elliott,9,Chevrolet,13,0,4.0,9.0,Chevrolet,4.0,0.0
3,4,Michael McDowell,71,Chevrolet,15,0,2.0,34.0,Ford,12.0,0.0
4,5,Christopher Bell,20,Toyota,10,0,9.0,20.0,Toyota,15.0,0.0
5,6,Tyler Reddick,45,Toyota,8,0,8.0,45.0,Toyota,2.0,0.0
6,7,Ty Gibbs,54,Toyota,6,0,37.0,54.0,Toyota,10.0,0.0
7,8,William Byron,24,Chevrolet,3,0,30.0,24.0,Chevrolet,6.0,0.0
8,9,Joey Logano,22,Ford,22,0,21.0,22.0,Ford,1.0,0.0
9,10,Kyle Busch,8,Chevrolet,17,0,12.0,8.0,Chevrolet,29.0,0.0
10,11,Brad Keselowski,6,Ford,21,0,13.0,6.0,Ford,35.0,0.0
11,12,Ryan Preece,60,Ford,20,0,18.0,41.0,Ford,30.0,0.0
12,13,Josh Berry,21,Ford,25,0,32.0,4.0,Ford,32.0,0.0
13,14,Daniel Suarez,99,Chevrolet,19,0,14.0,99.0,Chevrolet,7.0,0.0
14,15,Justin Haley,7,Chevrolet,29,0,33.0,51.0,Ford,27.0,0.0
15,16,Chris Buescher,17,Ford,14,0,3.0,17.0,Ford,26.0,0.0
16,17,Ty Dillon,10,Chevrolet,26,0,NaN,NaN,NaN,NaN,NaN
17,18,AJ Allmendinger,16,Chevrolet,5,0,6.0,16.0,Chevrolet,11.0,0.0
18,19,Alex Bowman,48,Chevrolet,9,0,15.0,48.0,Chevrolet,8.0,0.0
19,20,Denny Hamlin,11,Toyota,16,0,38.0,11.0,Toyota,25.0,0.0
20,21,Austin Dillon,3,Chevrolet,33,0,36.0,3.0,Chevrolet,16.0,0.0
21,22,Todd Gilliland,34,Ford,35,0,10.0,38.0,Ford,14.0,0.0
22,23,Cole Custer,41,Chevrolet,27,0,NaN,NaN,NaN,NaN,NaN
23,24,Ross Chastain,1,Chevrolet,4,0,5.0,1.0,Chevrolet,9.0,0.0
24,25,Riley Herbst,35,Toyota,28,0,NaN,NaN,NaN,NaN,NaN
25,26,Bubba Wallace,23,Toyota,30,0,20.0,23.0,Toyota,18.0,0.0
26,27,Zane Smith,38,Ford,12,0,16.0,71.0,Chevrolet,20.0,0.0
27,28,John Hunter Nemechek,42,Toyota,18,0,29.0,42.0,Toyota,37.0,0.0
28,29,Erik Jones,43,Toyota,31,0,19.0,43.0,Toyota,38.0,0.0
29,30,Austin Cindric,2,Ford,24,0,22.0,2.0,Ford,28.0,0.0
30,31,Katherine Legge,78,Chevrolet,37,0,NaN,NaN,NaN,NaN,NaN
31,32,Carson Hocevar,77,Chevrolet,23,0,17.0,77.0,Chevrolet,13.0,0.0
32,33,Ricky Stenhouse Jr.,47,Chevrolet,34,0,24.0,47.0,Chevrolet,33.0,0.0
33,34,Cody Ware,51,Chevrolet,36,0,NaN,NaN,NaN,NaN,NaN
34,35,Kyle Larson,5,Chevrolet,11,0,1.0,5.0,Chevrolet,5.0,0.0
35,36,Ryan Blaney,12,Ford,7,0,7.0,12.0,Ford,3.0,0.0
36,37,Noah Gragson,4,Ford,32,0,26.0,10.0,Ford,19.0,0.0

In [82]:
a = df_merged
a

,POS_x,DRIVER,CAR_x,MANUFACTURER_x,START_x,PENALTY_x,POS_y,CAR_y,MANUFACTURER_y,START_y,PENALTY_y
0,1,Shane van Gisbergen,88,Chevrolet,1,0,NaN,NaN,NaN,NaN,NaN
1,2,Chase Briscoe,19,Toyota,2,0,34.0,14.0,Ford,23.0,0.0
2,3,Chase Elliott,9,Chevrolet,13,0,4.0,9.0,Chevrolet,4.0,0.0
3,4,Michael McDowell,71,Chevrolet,15,0,2.0,34.0,Ford,12.0,0.0
4,5,Christopher Bell,20,Toyota,10,0,9.0,20.0,Toyota,15.0,0.0
5,6,Tyler Reddick,45,Toyota,8,0,8.0,45.0,Toyota,2.0,0.0
6,7,Ty Gibbs,54,Toyota,6,0,37.0,54.0,Toyota,10.0,0.0
7,8,William Byron,24,Chevrolet,3,0,30.0,24.0,Chevrolet,6.0,0.0
8,9,Joey Logano,22,Ford,22,0,21.0,22.0,Ford,1.0,0.0
9,10,Kyle Busch,8,Chevrolet,17,0,12.0,8.0,Chevrolet,29.0,0.0
10,11,Brad Keselowski,6,Ford,21,0,13.0,6.0,Ford,35.0,0.0
11,12,Ryan Preece,60,Ford,20,0,18.0,41.0,Ford,30.0,0.0
12,13,Josh Berry,21,Ford,25,0,32.0,4.0,Ford,32.0,0.0
13,14,Daniel Suarez,99,Chevrolet,19,0,14.0,99.0,Chevrolet,7.0,0.0
14,15,Justin Haley,7,Chevrolet,29,0,33.0,51.0,Ford,27.0,0.0
15,16,Chris Buescher,17,Ford,14,0,3.0,17.0,Ford,26.0,0.0
16,17,Ty Dillon,10,Chevrolet,26,0,NaN,NaN,NaN,NaN,NaN
17,18,AJ Allmendinger,16,Chevrolet,5,0,6.0,16.0,Chevrolet,11.0,0.0
18,19,Alex Bowman,48,Chevrolet,9,0,15.0,48.0,Chevrolet,8.0,0.0
19,20,Denny Hamlin,11,Toyota,16,0,38.0,11.0,Toyota,25.0,0.0
20,21,Austin Dillon,3,Chevrolet,33,0,36.0,3.0,Chevrolet,16.0,0.0
21,22,Todd Gilliland,34,Ford,35,0,10.0,38.0,Ford,14.0,0.0
22,23,Cole Custer,41,Chevrolet,27,0,NaN,NaN,NaN,NaN,NaN
23,24,Ross Chastain,1,Chevrolet,4,0,5.0,1.0,Chevrolet,9.0,0.0
24,25,Riley Herbst,35,Toyota,28,0,NaN,NaN,NaN,NaN,NaN
25,26,Bubba Wallace,23,Toyota,30,0,20.0,23.0,Toyota,18.0,0.0
26,27,Zane Smith,38,Ford,12,0,16.0,71.0,Chevrolet,20.0,0.0
27,28,John Hunter Nemechek,42,Toyota,18,0,29.0,42.0,Toyota,37.0,0.0
28,29,Erik Jones,43,Toyota,31,0,19.0,43.0,Toyota,38.0,0.0
29,30,Austin Cindric,2,Ford,24,0,22.0,2.0,Ford,28.0,0.0
30,31,Katherine Legge,78,Chevrolet,37,0,NaN,NaN,NaN,NaN,NaN
31,32,Carson Hocevar,77,Chevrolet,23,0,17.0,77.0,Chevrolet,13.0,0.0
32,33,Ricky Stenhouse Jr.,47,Chevrolet,34,0,24.0,47.0,Chevrolet,33.0,0.0
33,34,Cody Ware,51,Chevrolet,36,0,NaN,NaN,NaN,NaN,NaN
34,35,Kyle Larson,5,Chevrolet,11,0,1.0,5.0,Chevrolet,5.0,0.0
35,36,Ryan Blaney,12,Ford,7,0,7.0,12.0,Ford,3.0,0.0
36,37,Noah Gragson,4,Ford,32,0,26.0,10.0,Ford,19.0,0.0

In [16]:
def t(x: list) -> list:
    i = 0
    while i < len(x):
        yield x[i]
        i += 1

for y in t([13,2,3,4,200,300]):
    print(y)

13
2
3
4
200
300

In [ ]:
path = "./data/Sonoma/"
csv_files = glob.glob(path + "*.csv")
# https://www.youtube.com/watch?v=2uvysYbKdjM&t=330s
# frames = [process_your_file(f) for f in csv_files]
# result = pd.concat(frames)

import sqlalchemy
from sqlalchemy import create_engine

In [110]:
import psycopg2
import pandas.io.sql as sqlio
print('psycopg2 version:', psycopg2.__version__)
# con_string = dbname="beerme3", user=bob, password=admin, host=localhost, port=5432"  # default PostgreSQL port
conn = psycopg2.connect(dbname="beerme3", user="bob", password="admin", host="localhost", port=5432)
cur = conn.cursor()
sql = "select * from nascar_results where track = 'Bristol'"
df = sqlio.read_sql(sql, conn)
conn.close()
df.head()

psycopg2 version: 2.9.11 (dt dec pq3 ext lo64)

C:\Users\me\AppData\Local\Temp\ipykernel_37328\3421795696.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = sqlio.read_sql(sql, conn)

    race_date    track         driver  pos  greg_pick  bob_pick  track_id
0  2026-04-12  Bristol       Ty Gibbs    1      False      True        34
1  2026-04-12  Bristol    Ryan Blaney    2      False     False        34
2  2026-04-12  Bristol    Kyle Larson    3       True     False        34
3  2026-04-12  Bristol  Tyler Reddick    4      False     False        34
4  2026-04-12  Bristol  Chase Briscoe    5      False     False        34

In [112]:
import sqlalchemy
from sqlalchemy import create_engine
user_name = "bob"
password = "admin"
host = "localhost"
port = 5432
dbname = "beerme3"
connection_string = f"postgresql+psycopg2://{user_name}:{password}@{host}:{port}/{dbname}"

print('sqlalchemy version:', sqlalchemy.__version__)
con_string = "dbname='beerme3' user='bob' password='admin' host='localhost' port='5432'"
# engine = create_engine(connection_string,echo=True) # echo=True logs queries
engine = create_engine(connection_string) # echo=True logs queries
conn = engine.connect()
print(f"Connection Successful!")
sql = """select * from nascar_results"""
df_read_sql = pd.read_sql(sql, engine)
df_read_sql.describe()
conn.close()

sqlalchemy version: 2.0.51
Connection Successful!

In [122]:
from sqlalchemy.engine import URL

url_object = URL.create(
"postgresql+psycopg2",
username="bob",
password="admin", # no need to escape
host="localhost",
port=5432,
database="beerme3"
)

engine = create_engine(url_object)
conn = engine.connect()
print(f"Connection Successful!")
sql = """select * from nascar_results where track = 'Bristol' and (greg_pick=True or bob_pick=True)"""
df_read_sql = pd.read_sql(sql, engine)
df_read_sql
# conn.close()

Connection Successful!

    race_date    track       driver  pos  greg_pick  bob_pick  track_id
0  2026-04-12  Bristol     Ty Gibbs    1      False      True        34
1  2026-04-12  Bristol  Kyle Larson    3       True     False        34